#!/bin/bash

#gcc -E -DBLOCK=4 -DDATA_TYPE_SIZE=2 -DDST_EXT_OFFSET=12 -DINNER_OFFSET=4 -DN_INPUTS=3 -DOFFSET0=0 -DOFFSET1=1 -DOFFSET2=2 -DOFFSET3=3 -DSCALES_MASK=7 -DSCALE_DST=1 -DSIMD=1 -DSRC0_EXT_OFFSET=4 -DSRC1_EXT_OFFSET=4 -DSRC2_EXT_OFFSET=4 ./concat.c
gcc -E  -DBLOCK=1 -DDATA_TYPE_SIZE=2 -DDST_EXT_OFFSET=12 -DINNER_OFFSET=4 -DN_INPUTS=3 -DOFFSET0=0 -DOFFSET1=1 -DOFFSET2=2 -DOFFSET3=3 -DSCALES_MASK=0 -DSCALE_DST=1 -DSIMD=1 -DSRC0_EXT_OFFSET=4 -DSRC1_EXT_OFFSET=4 -DSRC2_EXT_OFFSET=4 ./concat.c
#gcc -E -DBLOCK=1 -DDATA_TYPE_SIZE=2 -DDST_EXT_OFFSET=12 -DINNER_OFFSET=4 -DN_INPUTS=3 -DOFFSET0=0 -DOFFSET1=1 -DOFFSET2=2 -DOFFSET3=3 -DSCALES_MASK=7 -DSCALE_DST=1 -DSIMD=1 -DSRC0_EXT_OFFSET=4 -DSRC1_EXT_OFFSET=4 -DSRC2_EXT_OFFSET=4 ./concat.c
cat concat.c > ./oneDNN/src/gpu/ocl/simple_concat.cl

